import { createFileRoute } from "@tanstack/react-router";
import { LegalShell } from "@/components/site-chrome";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms & Conditions — IntelliVerse AI" },
      {
        name: "description",
        content:
          "The rules for using IntelliVerse AI: account responsibilities, acceptable use, intellectual property, and limitation of liability.",
      },
      { property: "og:title", content: "Terms & Conditions — IntelliVerse AI" },
      {
        property: "og:description",
        content:
          "Read the terms that govern your use of IntelliVerse AI, including account, IP, and liability terms.",
      },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <LegalShell
      title="Terms and Conditions"
      subtitle={`Last updated ${new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" })}`}
    >
      <p>
        Welcome to IntelliVerse AI. By accessing or using our website and
        services (the "Services"), you agree to be bound by these Terms and
        Conditions. If you do not agree, do not use the Services.
      </p>

      <h2>1. Eligibility & accounts</h2>
      <ul>
        <li>You must be at least 13 years old (or the age of digital consent in your jurisdiction) to use the Services.</li>
        <li>You are responsible for providing accurate registration information and keeping it current.</li>
        <li>You are responsible for all activity that occurs under your account and for keeping your credentials confidential.</li>
        <li>Notify us immediately of any unauthorized use of your account.</li>
      </ul>

      <h2>2. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Services to violate any law or third-party rights.</li>
        <li>Upload malware, illegal content, or content that infringes intellectual property.</li>
        <li>Attempt to reverse-engineer, disrupt, or overload our infrastructure.</li>
        <li>Use the Services to generate content that is harmful, deceptive, harassing, or otherwise abusive.</li>
        <li>Resell, sublicense, or share access to your account without our written permission.</li>
      </ul>

      <h2>3. User content</h2>
      <p>
        You retain ownership of the prompts, files, and content you submit
        ("User Content"). You grant us a limited, non-exclusive license to
        host, process, and transmit your User Content solely to provide and
        improve the Services for you. You are responsible for ensuring you
        have the rights necessary to submit your User Content.
      </p>

      <h2>4. AI-generated output</h2>
      <p>
        Outputs generated by the AI are provided "as is". AI systems can make
        mistakes — verify important information before relying on it. To the
        extent permitted by law, you own the output you generate, subject to
        third-party rights and these Terms.
      </p>

      <h2>5. Intellectual property</h2>
      <p>
        IntelliVerse AI, the brand, the underlying software, design, and all
        related materials are owned by us or our licensors and are protected
        by intellectual property laws. Nothing in these Terms transfers
        ownership of our IP to you. You may not copy, modify, or create
        derivative works of our Services except as expressly permitted.
      </p>

      <h2>6. Subscriptions, fees & cancellation</h2>
      <p>
        Paid features, if any, are billed in advance on a recurring basis
        until cancelled. You can cancel at any time; cancellation takes
        effect at the end of the current billing period. Fees are
        non-refundable except where required by law.
      </p>

      <h2>7. Termination</h2>
      <p>
        We may suspend or terminate your access if you violate these Terms or
        if we are required to do so by law. You may stop using the Services
        and delete your account at any time.
      </p>

      <h2>8. Disclaimers</h2>
      <p>
        The Services are provided "as is" and "as available" without
        warranties of any kind, express or implied, including merchantability,
        fitness for a particular purpose, and non-infringement.
      </p>

      <h2>9. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, IntelliVerse AI and its
        affiliates shall not be liable for any indirect, incidental, special,
        consequential, or punitive damages, or any loss of profits, revenue,
        data, or goodwill, arising out of or related to your use of the
        Services. Our total aggregate liability for any claim shall not
        exceed the greater of the amounts you paid us in the 12 months
        preceding the claim or USD 100.
      </p>

      <h2>10. Changes</h2>
      <p>
        We may update these Terms from time to time. Material changes will be
        notified in-app or by email. Continued use of the Services after
        changes take effect constitutes acceptance of the updated Terms.
      </p>

      <h2>11. Contact</h2>
      <p>
        Questions about these Terms? Reach us through our{" "}
        <a href="/contact" className="text-foreground underline">Contact page</a>.
      </p>
    </LegalShell>
  );
}
