/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiToolRouteImport } from './routes/api/tool'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiGenerateDocRouteImport } from './routes/api/generate-doc'
import { Route as ApiGenerateAudioRouteImport } from './routes/api/generate-audio'
import { Route as ApiDocActionRouteImport } from './routes/api/doc-action'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppToolsRouteImport } from './routes/_app/tools'
import { Route as AppStudioRouteImport } from './routes/_app/studio'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppStudioIndexRouteImport } from './routes/_app/studio.index'
import { Route as AppToolsSlugRouteImport } from './routes/_app/tools.$slug'
import { Route as AppStudioImageRouteImport } from './routes/_app/studio.image'
import { Route as AppStudioDocsRouteImport } from './routes/_app/studio.docs'
import { Route as AppStudioAudioRouteImport } from './routes/_app/studio.audio'
import { Route as AppDocumentsIdRouteImport } from './routes/_app/documents.$id'
import { Route as AppChatIdRouteImport } from './routes/_app/chat.$id'
import { Route as AppAdminProvidersRouteImport } from './routes/_app/admin.providers'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolRoute = ApiToolRouteImport.update({
  id: '/api/tool',
  path: '/api/tool',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateDocRoute = ApiGenerateDocRouteImport.update({
  id: '/api/generate-doc',
  path: '/api/generate-doc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateAudioRoute = ApiGenerateAudioRouteImport.update({
  id: '/api/generate-audio',
  path: '/api/generate-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocActionRoute = ApiDocActionRouteImport.update({
  id: '/api/doc-action',
  path: '/api/doc-action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppToolsRoute = AppToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppRoute,
} as any)
const AppStudioRoute = AppStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppStudioIndexRoute = AppStudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppStudioRoute,
} as any)
const AppToolsSlugRoute = AppToolsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppStudioImageRoute = AppStudioImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => AppStudioRoute,
} as any)
const AppStudioDocsRoute = AppStudioDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppStudioRoute,
} as any)
const AppStudioAudioRoute = AppStudioAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => AppStudioRoute,
} as any)
const AppDocumentsIdRoute = AppDocumentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDocumentsRoute,
} as any)
const AppChatIdRoute = AppChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppChatRoute,
} as any)
const AppAdminProvidersRoute = AppAdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/chat': typeof AppChatRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRouteWithChildren
  '/library': typeof AppLibraryRoute
  '/settings': typeof AppSettingsRoute
  '/studio': typeof AppStudioRouteWithChildren
  '/tools': typeof AppToolsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/doc-action': typeof ApiDocActionRoute
  '/api/generate-audio': typeof ApiGenerateAudioRoute
  '/api/generate-doc': typeof ApiGenerateDocRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/tool': typeof ApiToolRoute
  '/admin/providers': typeof AppAdminProvidersRoute
  '/chat/$id': typeof AppChatIdRoute
  '/documents/$id': typeof AppDocumentsIdRoute
  '/studio/audio': typeof AppStudioAudioRoute
  '/studio/docs': typeof AppStudioDocsRoute
  '/studio/image': typeof AppStudioImageRoute
  '/tools/$slug': typeof AppToolsSlugRoute
  '/studio/': typeof AppStudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/chat': typeof AppChatRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRouteWithChildren
  '/library': typeof AppLibraryRoute
  '/settings': typeof AppSettingsRoute
  '/tools': typeof AppToolsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/doc-action': typeof ApiDocActionRoute
  '/api/generate-audio': typeof ApiGenerateAudioRoute
  '/api/generate-doc': typeof ApiGenerateDocRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/tool': typeof ApiToolRoute
  '/admin/providers': typeof AppAdminProvidersRoute
  '/chat/$id': typeof AppChatIdRoute
  '/documents/$id': typeof AppDocumentsIdRoute
  '/studio/audio': typeof AppStudioAudioRoute
  '/studio/docs': typeof AppStudioDocsRoute
  '/studio/image': typeof AppStudioImageRoute
  '/tools/$slug': typeof AppToolsSlugRoute
  '/studio': typeof AppStudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/chat': typeof AppChatRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRouteWithChildren
  '/_app/library': typeof AppLibraryRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/studio': typeof AppStudioRouteWithChildren
  '/_app/tools': typeof AppToolsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/doc-action': typeof ApiDocActionRoute
  '/api/generate-audio': typeof ApiGenerateAudioRoute
  '/api/generate-doc': typeof ApiGenerateDocRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/tool': typeof ApiToolRoute
  '/_app/admin/providers': typeof AppAdminProvidersRoute
  '/_app/chat/$id': typeof AppChatIdRoute
  '/_app/documents/$id': typeof AppDocumentsIdRoute
  '/_app/studio/audio': typeof AppStudioAudioRoute
  '/_app/studio/docs': typeof AppStudioDocsRoute
  '/_app/studio/image': typeof AppStudioImageRoute
  '/_app/tools/$slug': typeof AppToolsSlugRoute
  '/_app/studio/': typeof AppStudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/library'
    | '/settings'
    | '/studio'
    | '/tools'
    | '/api/chat'
    | '/api/doc-action'
    | '/api/generate-audio'
    | '/api/generate-doc'
    | '/api/generate-image'
    | '/api/tool'
    | '/admin/providers'
    | '/chat/$id'
    | '/documents/$id'
    | '/studio/audio'
    | '/studio/docs'
    | '/studio/image'
    | '/tools/$slug'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/library'
    | '/settings'
    | '/tools'
    | '/api/chat'
    | '/api/doc-action'
    | '/api/generate-audio'
    | '/api/generate-doc'
    | '/api/generate-image'
    | '/api/tool'
    | '/admin/providers'
    | '/chat/$id'
    | '/documents/$id'
    | '/studio/audio'
    | '/studio/docs'
    | '/studio/image'
    | '/tools/$slug'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/library'
    | '/_app/settings'
    | '/_app/studio'
    | '/_app/tools'
    | '/api/chat'
    | '/api/doc-action'
    | '/api/generate-audio'
    | '/api/generate-doc'
    | '/api/generate-image'
    | '/api/tool'
    | '/_app/admin/providers'
    | '/_app/chat/$id'
    | '/_app/documents/$id'
    | '/_app/studio/audio'
    | '/_app/studio/docs'
    | '/_app/studio/image'
    | '/_app/tools/$slug'
    | '/_app/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDocActionRoute: typeof ApiDocActionRoute
  ApiGenerateAudioRoute: typeof ApiGenerateAudioRoute
  ApiGenerateDocRoute: typeof ApiGenerateDocRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiToolRoute: typeof ApiToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tool': {
      id: '/api/tool'
      path: '/api/tool'
      fullPath: '/api/tool'
      preLoaderRoute: typeof ApiToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-doc': {
      id: '/api/generate-doc'
      path: '/api/generate-doc'
      fullPath: '/api/generate-doc'
      preLoaderRoute: typeof ApiGenerateDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-audio': {
      id: '/api/generate-audio'
      path: '/api/generate-audio'
      fullPath: '/api/generate-audio'
      preLoaderRoute: typeof ApiGenerateAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doc-action': {
      id: '/api/doc-action'
      path: '/api/doc-action'
      fullPath: '/api/doc-action'
      preLoaderRoute: typeof ApiDocActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tools': {
      id: '/_app/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AppToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/studio': {
      id: '/_app/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AppStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/studio/': {
      id: '/_app/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof AppStudioIndexRouteImport
      parentRoute: typeof AppStudioRoute
    }
    '/_app/tools/$slug': {
      id: '/_app/tools/$slug'
      path: '/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof AppToolsSlugRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/_app/studio/image': {
      id: '/_app/studio/image'
      path: '/image'
      fullPath: '/studio/image'
      preLoaderRoute: typeof AppStudioImageRouteImport
      parentRoute: typeof AppStudioRoute
    }
    '/_app/studio/docs': {
      id: '/_app/studio/docs'
      path: '/docs'
      fullPath: '/studio/docs'
      preLoaderRoute: typeof AppStudioDocsRouteImport
      parentRoute: typeof AppStudioRoute
    }
    '/_app/studio/audio': {
      id: '/_app/studio/audio'
      path: '/audio'
      fullPath: '/studio/audio'
      preLoaderRoute: typeof AppStudioAudioRouteImport
      parentRoute: typeof AppStudioRoute
    }
    '/_app/documents/$id': {
      id: '/_app/documents/$id'
      path: '/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AppDocumentsIdRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/_app/chat/$id': {
      id: '/_app/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AppChatIdRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/_app/admin/providers': {
      id: '/_app/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AppAdminProvidersRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminProvidersRoute: typeof AppAdminProvidersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminProvidersRoute: AppAdminProvidersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppChatRouteChildren {
  AppChatIdRoute: typeof AppChatIdRoute
}

const AppChatRouteChildren: AppChatRouteChildren = {
  AppChatIdRoute: AppChatIdRoute,
}

const AppChatRouteWithChildren =
  AppChatRoute._addFileChildren(AppChatRouteChildren)

interface AppDocumentsRouteChildren {
  AppDocumentsIdRoute: typeof AppDocumentsIdRoute
}

const AppDocumentsRouteChildren: AppDocumentsRouteChildren = {
  AppDocumentsIdRoute: AppDocumentsIdRoute,
}

const AppDocumentsRouteWithChildren = AppDocumentsRoute._addFileChildren(
  AppDocumentsRouteChildren,
)

interface AppStudioRouteChildren {
  AppStudioAudioRoute: typeof AppStudioAudioRoute
  AppStudioDocsRoute: typeof AppStudioDocsRoute
  AppStudioImageRoute: typeof AppStudioImageRoute
  AppStudioIndexRoute: typeof AppStudioIndexRoute
}

const AppStudioRouteChildren: AppStudioRouteChildren = {
  AppStudioAudioRoute: AppStudioAudioRoute,
  AppStudioDocsRoute: AppStudioDocsRoute,
  AppStudioImageRoute: AppStudioImageRoute,
  AppStudioIndexRoute: AppStudioIndexRoute,
}

const AppStudioRouteWithChildren = AppStudioRoute._addFileChildren(
  AppStudioRouteChildren,
)

interface AppToolsRouteChildren {
  AppToolsSlugRoute: typeof AppToolsSlugRoute
}

const AppToolsRouteChildren: AppToolsRouteChildren = {
  AppToolsSlugRoute: AppToolsSlugRoute,
}

const AppToolsRouteWithChildren = AppToolsRoute._addFileChildren(
  AppToolsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppChatRoute: typeof AppChatRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRouteWithChildren
  AppLibraryRoute: typeof AppLibraryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudioRoute: typeof AppStudioRouteWithChildren
  AppToolsRoute: typeof AppToolsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppChatRoute: AppChatRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRouteWithChildren,
  AppLibraryRoute: AppLibraryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudioRoute: AppStudioRouteWithChildren,
  AppToolsRoute: AppToolsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDocActionRoute: ApiDocActionRoute,
  ApiGenerateAudioRoute: ApiGenerateAudioRoute,
  ApiGenerateDocRoute: ApiGenerateDocRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiToolRoute: ApiToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
