// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'
import { getCachedAccessToken, setAuthTokenSession } from '@/lib/auth-token-cache'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    let token = getCachedAccessToken()
    if (!token) {
      const { data } = await supabase.auth.getSession()
      setAuthTokenSession(data.session)
      token = data.session?.access_token ?? null
    }
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
